### ISSUE TITLE
Plugin "Separate Users" breaks yourls 1.5

### ISSUE THREAD

**Issue by ozh** [ianbarber/Yourls-Separate-Users#1]
FYI a user reported this: http://code.google.com/p/yourls/issues/detail?id=1028

**Comment by ianbarber** [comment]
Thanks, I'll fix.

On Fri, Jan 27, 2012 at 3:44 PM, Ozh <
reply@reply.github.com

**Comment by ianbarber** [comment]
Can't reproduce right now with a fresh install and 1.5 from trunk. I'll leave this open in case anyone else finds the same issue!

**Comment by 98827ddb7e5a2c2e261912a23d9251d6** [comment]
Simply add a "user" column in the table "yourls_url" will fix all the problems. Works fine on my YOURLs 1.5.1  
;-)

![example](http://u.beryl.at/VAk3i)

note:The link on top was created after the modification.

**Comment by 98827ddb7e5a2c2e261912a23d9251d6** [comment]
Im trying to add a new column in the admin interface to show the creator of each link.   ;-)

**Comment by ianbarber** [comment]
That should happen when the plugin is activated - was it marked as activated?

**Comment by 98827ddb7e5a2c2e261912a23d9251d6** [comment]
Yes, it was activated. But the new column has not been created automatically. Once i did that manually, things started to go right.
