### ISSUE TITLE
if you find any users can see all links, try.....

### ISSUE THREAD

**Issue by catalas** [ianbarber/Yourls-Separate-Users#2]
OPEN plugin.php 
CHANGE yourls_add_action( 'admin_list_where', 'separate_users_admin_list_where' ); TO yourls_add_filter( 'admin_list_where', 'separate_users_admin_list_where' );

it is because admin_list_where is a filter in the latest hooklist

let me know for any problems. catalas@gmail.com

**Comment by luixxiul** [comment]
thanks, that works.

**Comment by ianbarber** [comment]
Thanks, merged that change in.
