### ISSUE TITLE
Quick Question

### ISSUE THREAD

**Issue by Alinya** [ianbarber/Yourls-Separate-Users#6]
Is it possible for this plugin to show who made which link? Like if there are three users with accounts, and one without, it would show either their account names, or just "Anonymous".

**Comment by Alinya** [comment]
And does this also potentially affect people from being able to use any of the links that others made? As in preventing it for loading for those not logged into the admin panel.

**Comment by ianbarber** [comment]
Anyone will be able to follow the shortlink, but only the user that created (or the admin) will be able to edit the link if I remember correctly. Worth noting this plugin is quite old, so I'm not sure how well it runs on the current versions of YouRLS.

**Comment by Alinya** [comment]
Thank you :)
